config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  resources :items
  resources :users
  resources :orders, only: [:index, :show]
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :order_items
  has_many :orders, through: :order_items
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user

  has_many :order_items
  has_many :items, through: :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find_by(id: params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_path, notice: "The item was created."
    else
      flash.now[:notice] = "The item was not created."
      render :edit
    end
  end

  def edit
    @item = Item.find_by(id: params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update_attributes(item_params)
      redirect_to item_path(@item), notice: "The item was updated."
    else
      flash.now[:notice] = "The item was not updated."
      render :edit
    end
  end

  def destroy
    Item.destroy(params[:id])

    redirect_to items_path, notice: "The item was deleted."
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :image_url)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, notice: "The user was created."
    else
      flash.now[:notice] = "The user was not created."
      render :edit
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to user_path(@user), notice: "The user was updated."
    else
      flash.now[:notice] = "The user was not updated."
      render :edit
    end
  end

  def destroy
    User.destroy(params[:id])

    redirect_to users_path, notice: "The user was deleted."
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.erb
<div class="container">
  <div class="col-sm-12">
    <h1>Edit Item</h1>
  </div>
  <div class="col-sm-6">
    <%= form_for @item do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <%= f.submit "Edit Item", class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<div class="container">
  <div class="col-sm-12">
    <h1 class="pull-left"><%= @items.count %> Items</h1>
    <%= link_to "New Item", new_item_path, class: "btn btn-default pull-right" %>
  </div>
  <% @items.each do |item| %>
    <div class="col-sm-3">
      <h5><%= item.name %></h5>
      <%= link_to(image_tag(item.image_url), item_path(item)) %>
      <p>
        <%= item.description %>
      </p>
    </div>
  <% end %>
</div>

app/views/items/new.html.erb
<div class="container">
  <div class="col-sm-12">
    <h1>Create Item</h1>
  </div>
  <div class="col-sm-6">
    <%= form_for @item do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <%= f.submit "Create Item", class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<div class="container">
  <div class="col-sm-3">
    <h5><%= @item.name %></h5>
    <%= image_tag(@item.image_url) %>
    <p>
      <%= @item.description %>
    </p>
    <p>
      <%= link_to "Edit Item", edit_item_path(@item), class: "btn btn-default" %>
    </p>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button class="navbar-toggle" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Storedom</a>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li>
        <a href="/">Items</a>
      </li>
      <li>
        <a href="/users">Users</a>
      </li>
      <li>
        <a href="/orders">Orders</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <title>Storedom</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="container">
  <div class="col-sm-12">
    <h1><%= @orders.count %> Orders</h1>
  </div>
  <% @orders.each do |order| %>
    <div class="col-sm-12">
      <h2>Order <%= order.id %></h2>
      <h5>Client: <%= order.user.name %></h5>
      <h5>Order Items</h5>
      <% order.items.each_with_index do |item, index| %>
        <p>
          <%= "#{index + 1}. #{item.name}" %>
        </p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="col-sm-12">
    <h1>Edit User</h1>
  </div>
  <div class="col-sm-6">
    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_area :email, class: "form-control" %>
      </div>
      <%= f.submit "Edit User", class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="col-sm-12">
    <h1 class="pull-left"><%= @users.count %> Users</h1>
    <%= link_to "New User", new_user_path, class: "btn btn-default pull-right" %>
  </div>
  <% @users.each do |user| %>
    <div class="col-sm-12">
      <h2> <%= link_to user.name, user_path(user) %></h2>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="col-sm-12">
    <h1>Create User</h1>
  </div>
  <div class="col-sm-6">
    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <%= f.submit "Create User", class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="col-sm-3">
    <h5><%= @user.name %></h5>
    <p>
      <%= @user.email %>
    </p>
    <p>
      <%= link_to "Edit User", edit_user_path(@user), class: "btn btn-default" %>
    </p>
  </div>
</div>